pipeline:
  name: s3Upload
  identifier: s3Upload
  projectIdentifier: Serverless
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s3Upload
        identifier: s3Upload
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.EKS
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: CreateFile
                  identifier: CreateFile
                  spec:
                    connectorRef: account.harnessImage
                    image: bash
                    shell: Bash
                    command: echo "Hello, World" > helloworld.txt
                    privileged: true
                    envVariables:
                      plugin_artifact_file: /harness/artifact/artifacts.json
                  failureStrategies: []
              - step:
                  type: S3Upload
                  name: s3Upload
                  identifier: s3Upload
                  spec:
                    connectorRef: org.AWS
                    region: us-east-2
                    bucket: harness-sam
                    sourcePath: helloworld.txt
              - step:
                  type: Run
                  name: SeeFiles
                  identifier: SeeFiles
                  spec:
                    connectorRef: account.harnessImage
                    image: bash
                    shell: Bash
                    command: |-

                      ls
                      mkdir -p artifact

                      json='{
                        "kind": "fileUpload/v1",
                        "data": {
                          "fileArtifacts": [
                            {
                              "name": "helloworld",
                              "url": "true"
                            }
                            {
                              "name": "myArtiFat",
                              "url": "true"
                            }
                          ]
                        }
                      }' 

                      echo "$json" >> /harness/artifact/artifacts.json
                      cat /harness/artifact/artifacts.json
