pipeline:
  name: s3Upload
  identifier: s3Upload
  projectIdentifier: Serverless
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s3Upload
        identifier: s3Upload
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.EKS
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: CreateFile
                  identifier: CreateFile
                  spec:
                    connectorRef: account.harnessImage
                    image: bash
                    shell: Sh
                    command: |-
                      echo "Hello, World" > helloworld.txt

                      mkdir -p artifact

                      cat >$PLUGIN_ARTIFACT_FILE << 'EOF'
                      {
                        "kind": "fileUpload/v1",
                        "data": {
                          "fileArtifacts": [
                            {
                              "name": "helloWorld",
                              "url": "true"
                            }
                            {
                              "name": "myArtiFat",
                              "url": "true"
                            }
                          ]
                        }
                      } 
                      EOF
                    envVariables:
                      plugin_artifact_file: /harness/artifact/artifacts.json
              - step:
                  type: S3Upload
                  name: s3Upload
                  identifier: s3Upload
                  spec:
                    connectorRef: org.AWS
                    region: us-east-2
                    bucket: harness-sam
                    sourcePath: helloworld.txt
