pipeline:
  name: s3Upload
  identifier: s3Upload
  projectIdentifier: Serverless
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s3Upload
        identifier: s3Upload
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.EKS
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: CreateFile
                  identifier: CreateFile
                  spec:
                    connectorRef: account.harnessImage
                    image: bash
                    shell: Bash
                    command: echo "Hello, World" > helloworld.txt
                    privileged: true
                    envVariables:
                      PLUGIN_ARTIFACT_FILE: /harness/artifact/artifacts.json
                  failureStrategies: []
              - step:
                  type: Plugin
                  name: mansong-s3
                  identifier: mansongs3
                  spec:
                    connectorRef: org.Dockerhub
                    image: mansong/s3:latest
                    settings:
                      bucket: harness-sam
                      source: helloworld.txt
                      region: us-east-2
                      access_key: <+secrets.getValue('AWS_ACCESS_KEY_ID')>
                      secret_key: <+secrets.getValue('AWS_SECRET_ACCESS_KEY')>
              - step:
                  type: S3Upload
                  name: s3Upload
                  identifier: s3Upload
                  spec:
                    connectorRef: org.AWS
                    region: us-east-2
                    bucket: harness-sam
                    sourcePath: helloworld.txt
                  failureStrategies: []
              - step:
                  type: Run
                  name: SeeFiles
                  identifier: SeeFiles
                  spec:
                    connectorRef: account.harnessImage
                    image: bash
                    shell: Bash
                    command: |-
                      ls
                      # mkdir -p artifact

                      # json='{
                      #   "kind": "fileUpload/v1",
                      #   "data": {
                      #     "fileArtifacts": [
                      #       {
                      #         "name": "helloworld",
                      #         "url": "true"
                      #       }
                      #       {
                      #         "name": "myArtiFat",
                      #         "url": "true"
                      #       }
                      #     ]
                      #   }
                      # }' 

                      # echo "$json" >> /harness/artifact/artifacts.json
                      cat /harness/artifact/artifacts.json
                  when:
                    stageStatus: Success
                    condition: "false"
                  failureStrategies: []
